import { Background, Controls, MiniMap, ReactFlow, type Edge, type Node } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { Network } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import AppShell from '../layouts/AppShell';
import PageHeader from '../components/PageHeader';
import PatientTabs from '../components/PatientTabs';
import { api } from '../services/api';

const palette:Record<string,string>={patient:'#0e7490',symptom:'#ea580c',condition:'#7c3aed',medication:'#0284c7',lab:'#059669',allergy:'#dc2626',doctor:'#475569',consultation:'#ca8a04',document:'#6366f1'};
export default function GraphPage(){const{id=''}=useParams();const[data,setData]=useState<any>({nodes:[],edges:[]});const[selected,setSelected]=useState<any>(null);useEffect(()=>{api(`/patients/${id}/graph`).then(setData)},[id]);const nodes=useMemo<Node[]>(()=>layout(data.nodes),[data.nodes]);const edges=useMemo<Edge[]>(()=>data.edges.map((e:any)=>({...e,type:'smoothstep',animated:e.label==='SEEN_BY',label:e.label,style:{stroke:'#94a3b8'},labelStyle:{fontSize:9,fill:'#64748b'}})),[data.edges]);return <AppShell><PageHeader eyebrow="Connected patient history" title="Medical Graph" text="Generated dynamically from relational SQLite/PostgreSQL records. Zoom, pan and select nodes to inspect the connected history."/><PatientTabs id={id}/><div className="grid gap-5 lg:grid-cols-[1fr_260px]"><div className="card h-[620px] overflow-hidden"><ReactFlow nodes={nodes} edges={edges} fitView onNodeClick={(_,n)=>setSelected(n.data)}><Background/><Controls/><MiniMap/></ReactFlow></div><div className="card p-5"><div className="mb-4 flex items-center gap-2"><Network className="h-5 w-5 text-cyan-700"/><h2 className="font-bold">Node details</h2></div>{selected?<div><span className="badge">{String(selected.type).toUpperCase()}</span><div className="mt-4 text-lg font-bold">{selected.label}</div>{selected.subtitle&&<div className="mt-2 text-sm text-slate-500">{selected.subtitle}</div>}</div>:<p className="text-sm leading-6 text-slate-500">Select any patient, symptom, condition, medication, lab, doctor, consultation or document node.</p>}<div className="mt-8 space-y-2">{Object.entries(palette).map(([k,v])=><div key={k} className="flex items-center gap-2 text-xs text-slate-500"><span className="h-3 w-3 rounded-full" style={{background:v}}/>{k}</div>)}</div></div></div></AppShell>}
function layout(items:any[]):Node[]{if(!items.length)return[];const root=items.find(x=>x.type==='patient');const others=items.filter(x=>x!==root);const cx=520,cy=310,r=245;const list:any[]=[];if(root)list.push({id:root.id,position:{x:cx-90,y:cy-35},data:root,style:styleFor(root,true)});others.forEach((n,i)=>{const a=(Math.PI*2*i)/Math.max(others.length,1)-Math.PI/2;list.push({id:n.id,position:{x:cx+Math.cos(a)*r-85,y:cy+Math.sin(a)*r-30},data:n,style:styleFor(n,false)})});return list}
function styleFor(n:any,root:boolean){return{width:root?180:170,border:`1px solid ${palette[n.type]||'#64748b'}`,borderRadius:14,padding:10,background:'#fff',boxShadow:'0 8px 20px rgba(15,23,42,.08)',fontSize:12,fontWeight:700,color:'#0f172a'}}
