import { ArrowRight, BrainCircuit, FileText, Mic2, Network, ShieldCheck, Sparkles, Stethoscope } from 'lucide-react';
import { Link } from 'react-router-dom';

const features = [
  { icon: Mic2, title: 'SPEAK', text: 'Patients communicate naturally in Tamil, English, Hindi or Telugu.' },
  { icon: BrainCircuit, title: 'UNDERSTAND', text: 'AI converts voice and medical documents into structured medical information.' },
  { icon: Network, title: 'CONNECT', text: 'Approved information becomes part of one connected longitudinal patient history.' },
];
const steps = ['Patient Voice', 'AI Medical Understanding', 'Document Intelligence', 'Structured EHR', 'Connected Medical History', 'Doctor Insight'];

export default function LandingPage() {
  return <div className="min-h-screen overflow-hidden bg-white">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-700 text-white"><Stethoscope className="h-5 w-5"/></div><div><div className="font-bold text-slate-900">MediBridge AI</div><div className="text-xs text-slate-500">Research prototype</div></div></div><div className="flex items-center gap-2"><Link to="/login" className="btn-secondary">Login</Link><Link to="/register" className="btn-primary">Get Started</Link></div></header>
    <section className="relative border-y border-slate-100 bg-gradient-to-br from-cyan-50 via-white to-teal-50"><div className="absolute -right-24 -top-24 h-96 w-96 rounded-full bg-cyan-200/30 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-28"><div><div className="badge mb-5"><Sparkles className="mr-1.5 h-3.5 w-3.5"/>AI-powered healthcare documentation</div><h1 className="max-w-4xl text-5xl font-black tracking-tight text-slate-950 sm:text-6xl">MediBridge <span className="text-cyan-700">AI</span></h1><p className="mt-5 max-w-2xl text-xl leading-8 text-slate-600">Bridging Patient Voice, Medical Documents and Intelligent Health Records.</p><p className="mt-6 max-w-2xl leading-7 text-slate-600">A multilingual clinical documentation prototype that turns unstructured patient voice and medical documents into editable, clinician-verifiable structured records.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/login" className="btn-primary px-5 py-3">Open Demo <ArrowRight className="h-4 w-4"/></Link><a href="#workflow" className="btn-secondary px-5 py-3">See workflow</a></div><div className="mt-8 flex items-center gap-2 text-sm text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-600"/>No diagnosis or prescribing. Clinician verification remains mandatory.</div></div>
      <div className="card relative overflow-hidden p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><div className="text-sm font-semibold text-slate-500">Unified Patient View</div><div className="mt-1 text-xl font-bold">Ravi Kumar • MB-P-1001</div></div><div className="rounded-xl bg-cyan-50 p-3 text-cyan-700"><BrainCircuit className="h-6 w-6"/></div></div><div className="grid grid-cols-2 gap-3"><Mini label="Known condition" value="Type 2 Diabetes"/><Mini label="Medication" value="Metformin"/><Mini label="Recent symptom" value="Fever • 3 days"/><Mini label="Recent lab" value="HbA1c • 7.4%"/></div><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">AI clinical summary</div><p className="text-sm leading-6 text-slate-600">Available records are summarized for pre-consultation review, with source data retained for clinician verification.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 md:grid-cols-3">{features.map(({icon:Icon,title,text}) => <div key={title} className="card p-6"><div className="mb-5 inline-flex rounded-2xl bg-cyan-50 p-3 text-cyan-700"><Icon className="h-6 w-6"/></div><div className="text-sm font-extrabold tracking-[.18em] text-cyan-700">{title}</div><p className="mt-3 leading-7 text-slate-600">{text}</p></div>)}</div></section>
    <section id="workflow" className="bg-slate-950 py-20 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><div className="text-sm font-bold uppercase tracking-[.18em] text-cyan-300">One connected workflow</div><h2 className="mt-3 text-3xl font-bold">From patient expression to doctor-ready context.</h2></div><div className="mt-10 grid gap-3 md:grid-cols-3 lg:grid-cols-6">{steps.map((s,i) => <div key={s} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="mb-4 grid h-8 w-8 place-items-center rounded-full bg-cyan-400/15 text-sm font-bold text-cyan-200">{i+1}</div><div className="text-sm font-semibold leading-5">{s}</div></div>)}</div></div></section>
    <footer className="border-t border-slate-100 px-5 py-7 text-center text-sm text-slate-500">MediBridge AI • Synthetic demo data only • Research / hackathon prototype</footer>
  </div>;
}
function Mini({label,value}:{label:string;value:string}) { return <div className="rounded-xl border border-slate-200 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-sm font-semibold text-slate-900">{value}</div></div> }
