import { BrainCircuit, Clock3, FileUp, Languages, Network, Pill, TestTube2, FileCheck2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import AppShell from '../layouts/AppShell';
import PageHeader from '../components/PageHeader';
import Disclaimer from '../components/Disclaimer';
import { api } from '../services/api';
import type { Patient } from '../types';

export default function PatientDashboard(){const[p,setP]=useState<Patient|null>(null);const[msg,setMsg]=useState('');useEffect(()=>{api<Patient>('/patients/me').then(setP)},[]);const changeLanguage=async(language:string)=>{if(!p)return;const updated=await api<Patient>(`/patients/${p.id}`,{method:'PATCH',body:JSON.stringify({preferredLanguage:language})});setP({...p,preferredLanguage:updated.preferredLanguage});setMsg('Preferred language updated.');};return <AppShell><PageHeader eyebrow="My health record" title={p?`Hello, ${p.name}`:'Patient Dashboard'} text="Use voice or manual text to prepare structured information, upload documents, and review approved history."/>
<Disclaimer/>{p&&<div className="card mt-6 flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-semibold">Preferred consultation language</div><div className="text-xs text-slate-500">Used as the default language context for the prototype workflow.</div></div><select className="input max-w-xs" value={p.preferredLanguage} onChange={e=>changeLanguage(e.target.value)}>{['English','Tamil','Hindi','Telugu'].map(x=><option key={x}>{x}</option>)}</select></div>}{msg&&<div className="mt-3 text-sm text-emerald-700">{msg}</div>}<div className="mt-6 grid gap-4 lg:grid-cols-4"><Link to="/voice-consultation" className="card p-6 transition hover:-translate-y-0.5"><BrainCircuit className="h-7 w-7 text-cyan-700"/><h2 className="mt-5 font-bold">Start voice consultation</h2><p className="mt-2 text-sm leading-6 text-slate-500">Speak in Tamil, English, Hindi or Telugu, then review AI-extracted information before saving.</p></Link><Link to="/document-upload" className="card p-6 transition hover:-translate-y-0.5"><FileUp className="h-7 w-7 text-cyan-700"/><h2 className="mt-5 font-bold">Upload medical document</h2><p className="mt-2 text-sm leading-6 text-slate-500">Prescription, lab report or discharge summary can be converted into editable structured data.</p></Link>{p&&<Link to={`/patients/${p.id}/timeline`} className="card p-6 transition hover:-translate-y-0.5"><Clock3 className="h-7 w-7 text-cyan-700"/><h2 className="mt-5 font-bold">View medical history</h2><p className="mt-2 text-sm leading-6 text-slate-500">See consultations, symptoms, medicines, labs and approved documents in one timeline.</p></Link>}{p&&<Link to={`/patients/${p.id}/summary`} className="card p-6 transition hover:-translate-y-0.5"><FileCheck2 className="h-7 w-7 text-cyan-700"/><h2 className="mt-5 font-bold">Approved AI summary</h2><p className="mt-2 text-sm leading-6 text-slate-500">View the latest clinician-approved documentation summary generated from your structured record.</p></Link>}</div>
{p&&<div className="mt-6 grid gap-4 md:grid-cols-4"><Mini icon={Languages} label="Preferred language" value={p.preferredLanguage}/><Mini icon={Pill} label="Active medicines" value={String(p.patientMedications?.filter((x:any)=>x.status==='ACTIVE').length||0)}/><Mini icon={TestTube2} label="Lab results" value={String(p.labResults?.length||0)}/><Mini icon={Network} label="Conditions" value={String(p.diagnoses?.length||0)}/></div>}</AppShell>}
function Mini({icon:Icon,label,value}:any){return <div className="card p-5"><Icon className="h-5 w-5 text-cyan-700"/><div className="mt-4 text-xl font-bold">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>}
