import { BrainCircuit, Copy, RefreshCw } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import AppShell from '../layouts/AppShell';
import PageHeader from '../components/PageHeader';
import PatientTabs from '../components/PatientTabs';
import Disclaimer from '../components/Disclaimer';
import { api } from '../services/api';
import { useAuth } from '../hooks/useAuth';
export default function SummaryPage(){const{id=''}=useParams();const{user}=useAuth();const[s,setS]=useState<any>(null);const[msg,setMsg]=useState('');const load=()=>api(`/patients/${id}/summary`).then(setS);useEffect(()=>{load()},[id]);const gen=async()=>{const r=await api(`/patients/${id}/summary`,{method:'POST'});setS(r);setMsg('New documentation summary generated from available structured records. Review it before approval.')};const approve=async()=>{if(!s)return;const r=await api(`/patients/${id}/summary/${s.id}/approve`,{method:'POST'});setS(r);setMsg('Summary approved for patient viewing.')};return <AppShell><PageHeader eyebrow="Doctor-ready context" title="AI Clinical Summary" text="Concise synthesis of information already present in the patient record. It does not infer a diagnosis or recommend treatment."/><PatientTabs id={id}/><Disclaimer/><div className="card mt-6 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-50 p-2.5 text-cyan-700"><BrainCircuit className="h-5 w-5"/></div><div><div className="font-bold">Clinical documentation summary</div><div className="text-xs text-slate-500">{s?`Generated ${new Date(s.createdAt).toLocaleString('en-IN')} • ${s.approved?'Approved':'Pending approval'}`:'No approved summary available yet'}</div></div></div><div className="flex gap-2">{s&&<button className="btn-secondary" onClick={()=>navigator.clipboard.writeText(s.summaryText)}><Copy className="h-4 w-4"/>Copy</button>}{(user?.role==='DOCTOR'||user?.role==='ADMIN')&&<><button className="btn-primary" onClick={gen}><RefreshCw className="h-4 w-4"/>Generate summary</button>{s&&!s.approved&&<button className="btn-secondary" onClick={approve}>Approve for patient</button>}</>}</div></div><div className="mt-6 min-h-64 whitespace-pre-wrap rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm leading-7 text-slate-700">{s?.summaryText||'A clinician can generate a summary after reviewing the available record.'}</div>{msg&&<div className="mt-4 text-sm text-emerald-700">{msg}</div>}</div></AppShell>}
